"""Add versioning fields

Revision ID: 74204de926e0
Revises: 
Create Date: 2025-12-11 10:06:41.917725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74204de926e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_response_versions', sa.Column('version_number', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('chat_response_versions', sa.Column('is_current', sa.Boolean(), nullable=False, server_default='true'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_invite_tokens_created_by'), table_name='invite_tokens')
    op.drop_index(op.f('idx_invite_tokens_token'), table_name='invite_tokens')
    op.alter_column('model_presets', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('model_presets', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('model_presets_name_key'), 'model_presets', type_='unique')
    op.create_index(op.f('ix_model_presets_id'), 'model_presets', ['id'], unique=False)
    op.create_index(op.f('ix_model_presets_name'), 'model_presets', ['name'], unique=True)
    op.drop_column('model_presets', 'max_tokens')
    op.drop_column('model_presets', 'top_p')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('model_presets', sa.Column('top_p', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.9'), autoincrement=False, nullable=True))
    op.add_column('model_presets', sa.Column('max_tokens', sa.INTEGER(), server_default=sa.text('2048'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_model_presets_name'), table_name='model_presets')
    op.drop_index(op.f('ix_model_presets_id'), table_name='model_presets')
    op.create_unique_constraint(op.f('model_presets_name_key'), 'model_presets', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('model_presets', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('model_presets', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('idx_invite_tokens_token'), 'invite_tokens', ['token'], unique=False)
    op.create_index(op.f('idx_invite_tokens_created_by'), 'invite_tokens', ['created_by'], unique=False)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('chat_response_versions', 'is_current')
    op.drop_column('chat_response_versions', 'version_number')
    # ### end Alembic commands ###
